import networkx as nx
from nl_querying.init_llm import LLM
import leidenalg
import igraph as ig
from typing import List, Tuple
import json, os



class IndexingService:
    def __init__(self, llm: LLM, community_path: str = "community_descriptions") -> None:
            self.community_path = community_path
            self.llm = llm

    def detect_communities(self, graph: nx.Graph) -> List[List[str]]:
        """
        Detects communities in a given NetworkX graph using the Leiden algorithm.

        This function converts the NetworkX graph into an igraph graph,
        applies the Leiden community detection algorithm with modularity optimization,
        and returns the detected communities as lists of node names.

        Parameters:
        -----------
        graph : nx.Graph
            The input graph in NetworkX format.

        Returns:
        --------
        List[List[str]]
            A list of communities, where each community is a list of node names.
        """
        nodes = list(graph.nodes())
        edges = list(graph.edges())

        g = ig.Graph()
        g.add_vertices(len(nodes))
        g.vs["name"] = nodes
        g.add_edges(edges)

        partition = leidenalg.find_partition(g, leidenalg.ModularityVertexPartition)

        return [[g.vs[v]['name'] for v in community] for community in partition]
    
    def describe_community(self, graph: nx.Graph, nodes: List[str]) -> str:
        """
        Generates a textual description of a subgraph (community) within a given NetworkX graph.

        This function creates a subgraph consisting of the specified nodes and constructs a textual
        summary of its structure. Each node is described with its label (from the 'node_type' attribute)
        and additional properties. Each edge is described with its source, target, type (from 'edge_type' 
        or 'label' attribute), and additional properties.

        Parameters:
        -----------
        graph : nx.Graph
            The input graph in NetworkX format.
        nodes : List[str]
            A list of node names or IDs representing the community to describe.

        Returns:
        --------
        str
            A textual description of the community, including nodes and their properties, and edges with
            their relationships and properties.
        """
        subgraph = graph.subgraph(nodes)

        node_descriptions = []
        for node_id in subgraph.nodes():
            data = subgraph.nodes[node_id]
            label = data.get("node_type", "Node")
            props = ", ".join(
                f"{k}: {v}" for k, v in data.items() if k not in ["x", "y"]
            )

            desc = f"{label}"
            if props:
                desc += f" [{props}]"
            node_descriptions.append(desc)

        edge_descriptions = []
        for source, target, data in subgraph.edges(data=True):
            source_name = subgraph.nodes[source].get("name") or source
            target_name = subgraph.nodes[target].get("name") or target
            rel_type = data.get("edge_type") or data.get("label") or "missing"

            props = ", ".join(
                f"{k}: {v}" for k, v in data.items() if k not in ["edge_type", "label"]
            )
            edge_text = f"{source_name} -[{rel_type}]-> {target_name}"
            if props:
                edge_text += f" [{props}]"
            edge_descriptions.append(edge_text)

        description = "Nodes:\n" + "\n".join(node_descriptions)
        description += "\nRelationships:\n" + "\n".join(edge_descriptions)
        return description 
    
    async def summarize_community_nl(self, graph: nx.Graph, community_nodes: List[str]) -> str:
        """
        Summarizes a specific community of nodes from a given graph using a language model.

        This asynchronous function takes a NetworkX graph and a list of node identifiers representing 
        a community within the graph. It generates a textual description of that community using the 
        `describe_community` method, then crafts a prompt instructing the language model to summarize 
        the community in natural language. The summary focuses on explaining the types of entities 
        (Person, Vessel, Organization, Group, Location) and their interactions, and is designed to be 
        concise (4–7 sentences).

        Parameters:
        -----------
        graph : nx.Graph
            The input graph containing all nodes and edges.
        
        community_nodes : List[str]
            A list of node identifiers representing the community to be summarized.

        Returns:
        --------
        str
            A natural language summary of the community generated by the language model.
        """
        description = self.describe_community(graph, community_nodes)

        prompt = f"""
            You are given a group of related nodes and edges from a knowledge graph.

            Summarize what this group is about in natural language in 4–7 sentences.
            
            Keep in mind the diffent Types of Entities: Person, Vessel, Organization, Group, Location.
            And how such diffent Entities interact.


            Graph Section:
            {description}

            Only respond with a paragraph of natural language. Do not include code or metadata.
        """

        return await self.llm.invoke_prompt(
            system_prompt="You are a helpfull assistent.",
            user_prompt=prompt
        )
    
    async def summarize_all_communities(self, graph: nx.Graph):
        """
        Detects communities in the graph, assigns community labels to nodes,
        and generates natural language summaries for each community.

        This asynchronous function first uses the `detect_communities` method to partition
        the graph into communities. It then iterates through each community, labels the
        nodes in the graph with their respective community IDs, and uses the language model
        (via `summarize_community_nl`) to generate a concise summary describing each
        community's contents and structure.

        Parameters:
        -----------
        graph : nx.Graph
            The input graph in NetworkX format containing all nodes and edges.

        llm : object
            An instance of a language model interface that supports the `invoke_prompt` method
            (expected to be asynchronous).

        Returns:
        --------
        Tuple[nx.Graph, List[Tuple[int, str]]]
            A tuple containing:
                - The updated graph with node-level community labels assigned.
                - A list of tuples, each consisting of a community index and its corresponding
                natural language summary.
        """
        communities = self.detect_communities(graph)
        summaries = []

        for i, community in enumerate(communities):
            matched_nodes = []
            for node in community:
                if node in graph.nodes:
                    graph.nodes[node]["community"] = i
                    matched_nodes.append(node)

            summary = await self.summarize_community_nl(graph, matched_nodes)
            summaries.append((i, summary))

        return graph, summaries
    
    def write_community_descriptions(self, summaries: List[Tuple[int, str]]):
        """
        Writes the community summaries to JSON files.

        This function takes a list of community summaries (each containing a community index
        and its corresponding summary text) and writes them to individual JSON files in the
        directory specified by `self.community_path`. Each file is named `community_{i}.json`
        and contains the community index and the summary in a structured format.

        Parameters:
        -----------
        summaries : List[Tuple[int, str]]
            A list of tuples, each containing a community index (int) and a summary
            (str) describing that community.
        """
        os.makedirs(self.community_path, exist_ok=True)

        for i, summary in summaries:
            file_path = os.path.join(self.community_path, f"community_{i}.json")
            with open(file_path, "w", encoding="utf-8") as f:
                json.dump({
                    "community": i,
                    "summary": summary
                }, f, ensure_ascii=False, indent=2)

    async def add_graph_communities(self, graph: nx.Graph):
        """
        Detects communities in the graph, generates summaries, writes them to files,
        and returns the updated graph.

        This asynchronous function first calls `summarize_all_communities` to detect
        communities and generate summaries for each. It then writes the summaries to
        individual JSON files using `write_community_descriptions`. Finally, it returns
        the graph with community information added.

        Parameters:
        -----------
        graph : nx.Graph
            The input graph in NetworkX format containing all nodes and edges.

        Returns:
        --------
        nx.Graph
            The updated graph with node-level community labels assigned.
        """

        graph_with_communities, summaries = await self.summarize_all_communities(graph=graph)
        self.write_community_descriptions(summaries)
        return graph_with_communities
    
